upstreams:
- name: default-upstream
  addresses:
  - host: httpbin.org
    port: 80
    scheme: http

backends:
- type: redis
  name: redis

endpoints:
- name: all
  upstream: default-upstream
  backend: redis
  path: /{path}*
  method: GET
  key:
  - !Method
  - !Path
    path: /{path}*
  predicates:
    request: []
    response:
    - !StatusCode 200
