sign-commit = true
sign-tag = true
pre-release-commit-message = "Release {{crate_name}} {{version}} 🎉"
post-release-commit-message = "Start next {{crate_name}} development iteration {{next_version}}"
tag-message = "Release {{crate_name}} {{version}}"
tag-name = "{{prefix}}{{version}}"
no-dev-version = true

pre-release-replacements = [
  {file="CHANGELOG.md", search="\\[Unreleased\\]", replace="[{{version}}] {{date}}"},
  {file="CHANGELOG.md", search="\\(https://semver.org/spec/v2.0.0.html\\).", replace="(https://semver.org/spec/v2.0.0.html).\n\n## [Unreleased]"}
]
